//Generated by gopages, do not edit
//This file will be overwritten during build

package pages

import (
	"code.google.com/p/gopages/pkg"
)

func init() {
	gopages.ParsedPages["html/login.html"] = Renderhtmlloginhtml
	gopages.ParsedPages["html/register.html"] = Renderhtmlregisterhtml
	gopages.ParsedPages["html/index.html"] = Renderhtmlindexhtml
}
